[package]
name = "rustracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
glm = "0.2.3"
image = "0.24.5"
indicatif = "0.17.5"
num-traits = "0.2.15"
rand = "0.8.5"
rayon = "1.7.0"
structopt = "0.3.26"
xmltree = "0.10.3"
